version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: esha0ay/truthlens-backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: esha0ay/truthlens-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
