apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: truthlens-backend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: truthlens-backend
